include_guard(GLOBAL)

set(CMAKE_SYSTEM_NAME AmigaOS)
set(CMAKE_SYSTEM_PROCESSOR m68k)

set(M68K_CPU_TYPES "68000" "68010" "68020" "68040" "68060")
set(M68K_CPU "68060" CACHE STRING "Target CPU model")
set_property(CACHE M68K_CPU PROPERTY STRINGS ${M68K_CPU_TYPES})

set(M68K_FPU_TYPES "soft" "hard")
set(M68K_FPU "hard" CACHE STRING "FPU type")
set_property(CACHE M68K_FPU PROPERTY STRINGS ${M68K_FPU_TYPES})

set(M68K_TOOLCHAIN_PATH "/opt/amiga-debian" CACHE PATH
    "Path to the bebbo Amiga GCC 6.5.0b 241006 toolchain")
set(AMIGA_SUPPORT_PATH "/mnt/d/amiga-gcc2" CACHE PATH
    "Path containing the Amiga support headers and C2P objects")

set(CMAKE_SYSROOT "${M68K_TOOLCHAIN_PATH}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_FIND_LIBRARY_SUFFIXES ".a")

set(AMIGA 1)
set(AMIGAOS3 1)
set(BUILD "RELEASE")
set(BUILD_SHARED_LIBS OFF)

set(CMAKE_C_COMPILER "${M68K_TOOLCHAIN_PATH}/bin/m68k-amigaos-gcc")
set(CMAKE_CXX_COMPILER "${M68K_TOOLCHAIN_PATH}/bin/m68k-amigaos-g++")
set(CMAKE_CPP_COMPILER "${M68K_TOOLCHAIN_PATH}/bin/m68k-amigaos-cpp")
set(CMAKE_ASM_COMPILER "${M68K_TOOLCHAIN_PATH}/bin/m68k-amigaos-as")
set(CMAKE_PREFIX_PATH "${M68K_TOOLCHAIN_PATH}")

option(AMIGA_ENABLE_GPROF "Build with gprof instrumentation" OFF)
if(AMIGA_ENABLE_GPROF)
    set(AMIGA_PROFILE_FLAGS "-pg")
    set(AMIGA_FINAL_STRIP_FLAG "")
else()
    set(AMIGA_PROFILE_FLAGS "-s -fomit-frame-pointer")
    set(AMIGA_FINAL_STRIP_FLAG "-s")
endif()
set(AMIGA_COMMON_FLAGS
    "-m${M68K_CPU} -m${M68K_FPU}-float -O1 -fbbb=- -fno-strict-aliasing -fno-unroll-loops -DBR_ENDIAN_BIG=1 -DBUILD=RELEASE -w -std=gnu11 -noixemul ${AMIGA_PROFILE_FLAGS} -I${AMIGA_SUPPORT_PATH}/include -I${CMAKE_SOURCE_DIR}/src/DETHRACE/common -I${CMAKE_SOURCE_DIR}/src/DETHRACE -I${CMAKE_SOURCE_DIR}/src/S3/include")

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${AMIGA_COMMON_FLAGS}")
set(CMAKE_CXX_FLAGS
    "${CMAKE_CXX_FLAGS} ${AMIGA_COMMON_FLAGS} -D__stdargs= -std=c++11")

set(CMAKE_EXE_LINKER_FLAGS
    "${CMAKE_EXE_LINKER_FLAGS} ${AMIGA_PROFILE_FLAGS} -L${AMIGA_SUPPORT_PATH}/lib ${AMIGA_SUPPORT_PATH}/lib/c2p1x1_4_c5_bm.o ${AMIGA_SUPPORT_PATH}/lib/c2p1x1_8_c5_bm_040.o ${AMIGA_SUPPORT_PATH}/lib/c2p1x1_6_c5_bm_040.o -lm -noixemul ${AMIGA_FINAL_STRIP_FLAG}")
set(CMAKE_EXE_LINKER_FLAGS_DEBUG
    "${CMAKE_EXE_LINKER_FLAGS_DEBUG} -lm -DDEBUG -ldebug")
set(CMAKE_CXX_FLAGS_DEBUG "-DDEBUG")
